### ISSUE TITLE
What licence is this code released under?

### ISSUE THREAD

**Issue by ghane** [Tantiv4/RaspberryPI#2]
I see node.js files, which have an MIT licence.  

Would an MIT, BSD 2-clause, or CC-BY licence be appropriate?

**Comment by ljohri** [comment]
which one would you suggest?

**Comment by ghane** [comment]
MIT.  Same as node.js, BTW

-- 
Sanjeev Gupta
+65 98551208     http://www.linkedin.com/in/ghane

**Comment by ghane** [comment]
Added a Licence file, commit #3
